security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: auto

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            form_login:
                login_path: app_login
                check_path: app_login
                username_parameter: email
                password_parameter: password
                default_target_path: /dashboard

            logout:
                path: app_logout
                target: app_login

            # Lazy firewall (mode anonyme implicite)
            lazy: true

    access_control:
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/dashboard, roles: ROLE_USER }
